version: '3.4'
services:
  web:
    build: .
    ports:
      - "80:80"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: reporting_app
  rabbitmq:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
      - "15672:15672"
  orientdb:
    image: "orientdb:latest"
    ports:
        - "2424:2424"
        - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
