version: '3'
services:
  web:
    build: .
    hostname: final-server1
    ports:
      - "80:80"
  rabbitmq:
    image: "rabbitmq:3"
    hostname: rabbit-server1
    ports:
      - "5672:5672"
      - "15672:15672"
  orientdb:
    image: "orientdb:latest"
    hostname: orientdb-server1
    ports:
        - "2424:2424"
        - "2480:2480"
